version: "3"
services:
    nodeserver:
        image: node
        container_name: nodeserver
        restart: always
        build:
            context: ./app
        ports:
            - "3000:3000"
        networks:
            - node-network
        depends_on:
            - db
            - nginx
    nginx:
        image: nginx
        container_name: nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
        networks:
            - node-network
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0 && --init-file /var/lib/mysql/init.sql
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - node-network

networks:
  node-network:
    driver: bridge
