version: "3"
services:
    nodeserver:
        image: node
        container_name: nodeserver
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        command: node index.js
        restart: always
        tty: true
        build:
            context: ./app
        ports:
            - "3000:3000"
        networks:
            - node-network
        depends_on:
            - db
    nginx:
        image: nginx
        container_name: nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
        networks:
            - node-network
        depends_on:
            - nodeserver
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/init:/docker-entrypoint-initdb.d/:ro
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - node-network

networks:
  node-network:
    driver: bridge